### ISSUE TITLE
Snake Teleportation Issue

### ISSUE THREAD

**Issue by usyd-zgoh2991** [USYD-ELEC-1005-GROUP-1/Project2-USYD#1]
`
#teleport snake to other side of canvas
#currently head teleports, but other pieces cause game to end 
        if self.snake.position[0] == self.settings.width:
            self.snake.position[0] = 0
        
        if self.snake.position[1] == self.settings.height:
            self.snake.position [1] = 0
                    
        return reward
    
    def game_end(self):
        end = False
        #if self.snake.position[0] >= self.settings.width or self.snake.position[0] < 0:
            #end = True
        #if self.snake.position[1] >= self.settings.height or self.snake.position[1] < 0:
            #end = True
        if self.snake.segments[0] in self.snake.segments[1:]:
            end = True

        return end
    `

**Comment by ning-bao** [comment]
Have you solved this issue? I found it worked when the snake touches the right border but it doesn't work for the left and the up borders...

**Comment by usyd-zgoh2991** [comment]
not yet, will solve on friday, prepping report and submission template tomorrow.

Currently the snake will teleport the first piece of its body (head), however the rest will cause gameover to occur. 

Does this occur for you too?

**Comment by ning-bao** [comment]
Seems I'm not getting this issue right now, but yeah, there are definitely something going wrong here... I'm working on the game saving and database functions right now

**Comment by ning-bao** [comment]
Ahhhh actually I think it's the game's design here... I just realised the snake should be dead when it hits the wall... Let me revert it back.
